name: full_flutter_advanced_course
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # State management
  flutter_bloc: ^8.1.6
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  # for dependency injection
  get_it: ^8.0.3
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  # Networking
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.5
  pretty_dio_logger: ^1.4.0
  # localization
  intl: ^0.19.0
  easy_localization: ^3.0.7
  # for splash screen
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
